fix: ensure sbom is copied to `output-file`
anchore/sbom-action pull request #411
Opened 2023-04-10 23:10 UTC by gszr

Before this, the sbom file would only be copied to `output-file` if `upload-artifact` is true. However, the file may still be useful if upload is not enabled.

2023-04-11 13:18 UTC, kzantow requested changes
As it stands, this would break artifact upload functionality when `output-file` is unset. 

Additionally, you need to generate the `dist/*` files (this should have happened automatically if you ran `npm install`, which would have installed a git hook to do this), but you can manually run this using `npm run package`.

I think you should revert all changes here except removal of:
```
const outputFile = core.getInput("output-file");
  if (outputFile) {
    fs.copyFileSync(filePath, outputFile);
  }
```
and addition of:
```
const outputFile = core.getInput("output-file");
    if (outputFile) {
        fs.writeFileSync(outputFile, contents);
    }
```

2023-04-11 13:18 UTC, kzantow commented on src/github/SyftGithubAction.ts
> +      await uploadSbomArtifact(outputFile);
This should not change, it would only work if `output-file` is set.

2023-04-12 14:45 UTC, merged

2023-04-12 15:21 UTC, gszr commented
Thanks for reviewing / merging, @kzantow!

2023-06-06 16:16 UTC, zosocanuck commented
The ability to specify an `output-file` seems to be broken:

```
- name: Create SBOM
        uses: anchore/sbom-action@v0.14.2
        with:
          image: ${{ env.IMAGE }}
          artifact-name: sample-image.spdx
          output-file: ${{ github.workspace }}/sample-image.spdx
          upload-artifact: true

```
```
SBOM scan completed in: 4.115s
------------------------- Uploading workflow artifacts -------------------------
/tmp/sbom-action-1zzfZv/sample-image.spdx
```