fix: don't pass in a separate env. This makes it impossible to pass env vars via the action context to syft.
anchore/sbom-action pull request #455
Opened 2024-03-26 21:36 UTC by iNoahNothing

Signed-off-by: Noah Krause <krausenoah@gmail.com>

2024-03-26 23:14 UTC, kzantow requested changes
Thanks for the contribution.

What environment variables are you setting? Is there a reason you aren't using a configuration file? This action supports a configuration file, either by adding a `.syft.yaml` in the root of your repository or by using the `config` parameter.

Instead of picking up environment variables, if you can't use a configuration file, maybe a better solution would be to overload the `config` parameter to _also_ accept Yaml configuration? E.g. it could look something like this:
```yaml
      - uses: anchore/sbom-action@v0
        with:
          path: .
          config: |
            log:
              level: debug
            select-catalogers: javascript
```

Regardless, you'll need to get the files in `dist/` updated. This should happen automatically from a git commit hook, which should get installed when you `npm install`. You can also just run: `npm run package`.

2024-03-27 13:19 UTC, iNoahNothing commented on src/github/SyftGithubAction.ts
> +  process.env.SYFT_CHECK_FOR_APP_UPDATE = "false"
Thank you, I am not the best JS programmer so was looking for the right way to do this

2024-03-27 13:24 UTC, iNoahNothing commented
> What environment variables are you setting? 

@kzantow 
I am trying to set `TMPDIR` to update where `stereoscope` is downloading the image tarball to. Not having the local env passed into the `syft` run is making it impossible to change this.

> Regardless, you'll need to get the files in dist/ updated. This should happen automatically from a git commit hook, which should get installed when you npm install. You can also just run: `npm run package`.

Thanks! I couldn't figure out the right way to get those updated from the contributing docs.

2024-03-27 19:35 UTC, kzantow approved these changes

2024-03-27 20:07 UTC, merged